name: Validate Istio Manifests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Istioctl
        uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: '1.25.1'

      - name: Validate Istio manifests
        run: |
          find istio-components -type f -name "*.yaml" -o -name "*.yml" | while IFS= read -r file; do
            echo "Validating with istioctl: $file"
            istioctl validate -f "$file"
          done